### PR TITLE
Add Pixel Arty Theme, and Theme support to Renderer

### PR DESCRIPTION
**Pull request by coler706**
Adds A New Art-style for the sprites
ship_gray
ship_orange
And More
(Bullets, ship0, seekers are also redone)

### CODE REVIEW

**Comment by andylippitt** [comment]
this is extremely cool. and live. ;)
we'll figure out how to make them selectable.

**Comment by coler706** [comment]
I assume you mean have multiple of the art styles and make a menu for them?

**Comment by coler706** [comment]
I could make a pr with that functionality if you want

**Comment by modderme123** [comment]
I think other people might want to do this as well so we should have a system like karnage.io where you can upload mods to dropbox

**Comment by modderme123** [comment]
@coler706 Your graphics are awesome! I just added support for theming by dropbox. If you want to do any further theming just copy the template at https://www.dropbox.com/s/3ryhaa6boenvv2k/daudmod.zip

**Comment by coler706** [comment]
The fish scale in the theme should be 0.01, not 0.0625

**Comment by coler706** [comment]
https://www.dropbox.com/s/pyznpibq1y07z1v/daudmod.zip

**Pull request closed without merging**
